import Form from "@/components/pages/checkout/Form";
import GoBack from "@/components/pages/single-product/GoBack";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Audiophile Stores | Checkout",
  description: "Generated by create next app",
};

const CheckoutPage = () => {
  return (
    <div className="min-h-screen bg-[#F1F1F1] p-6 md:p-12">
      <GoBack />
      <div className="mx-auto mt-6 max-w-7xl">
        <div className="grid grid-cols-1 gap-8 lg:grid-cols-3">
          <Form />
        </div>
      </div>
    </div>
  );
};

export default CheckoutPage;
