import HeroSection from "@/components/pages/headphones/HeroSection";
import SecondProduct from "@/components/pages/headphones/SecondProduct";
import ThirdProduct from "@/components/pages/headphones/ThirdProduct";
import TopProduct from "@/components/pages/headphones/TopProduct";
import { AudioProductsSection } from "@/components/pages/home/ProductShowCase";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Headphones | Audiophile Stores",
  description: "Generated by create next app",
};

export default function Page() {
  return (
    <>
      <HeroSection />
      <TopProduct />
      <SecondProduct />
      <ThirdProduct />
      <AudioProductsSection />
    </>
  );
}
