import HeroSection from "@/components/pages/earphones/HeroSection";
import TopProduct from "@/components/pages/earphones/TopProduct";
import { AudioProductsSection } from "@/components/pages/home/ProductShowCase";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Earphones | Audiophile Stores",
  description: "Generated by create next app",
};

export default function Page() {
  return (
    <>
      <HeroSection />
      <TopProduct />
      <AudioProductsSection />
    </>
  );
}
